### ISSUE TITLE
Question about MFEM wrapper version used in notebooks

### ISSUE THREAD

**Issue by sshiraiwa** [GLVis/pyglvis#19]
PyMFEM version 4.3.0.0 is out and I noticed mfem wrapper loaded in notebook is still 4.2.0.16.
I incremented the version written in https://github.com/mfem/PyMFEM/blob/master/binder/requirements.txt.
But, this does not (perhaps obviously) impact the notebook under here. Where is the version requirement encoded?

**Comment by tzanio** [comment]
We should also probably increment also here: https://github.com/GLVis/pyglvis/blob/master/requirements.txt

**Comment by tzanio** [comment]
@tomstitt, can you help?

**Comment by tomstitt** [comment]
> We should also probably increment also here: https://github.com/GLVis/pyglvis/blob/master/requirements.txt

@tzanio you are correct! I'm happy to bump it
