### ISSUE TITLE
About In-memory data transfer to glvis

### ISSUE THREAD

**Issue by sshiraiwa** [GLVis/pyglvis#4]
Hi,

Base on the previous discussion, WriteToStream is added in PyMFEM (https://github.com/mfem/PyMFEM/pull/55). This allows to write a data from Mesh/Gridfunction/Vector object to io.IOString. I think this allows to eliminate a need to write a temporary file in https://github.com/GLVis/pyglvis/blob/master/glvis/widget.py#L25. Please use 4.2.0.8

**Comment by tzanio** [comment]
Thank you @sshiraiwa !

**Comment by tzanio** [comment]
@rw-anderson, fyi you can now `WriteToStream` directly in PyMFEM see also #6 🎉
